<?php
    if(!isset($_GET['viewpop'])){
		$this->load->view('parts/head');
		$this->load->view('parts/topNav');
		$this->load->view('parts/body');
		if(isset($load_js))
			$this->load->view('js/'.$load_js.".php");
		$this->load->view('parts/foot');
    }
    else{
    	$this->load->view('parts/load');
    }
?>