<?php
function yearsPage($det=array()){
	$CI =& get_instance();
	$CI->html->sDivRow();
		$CI->html->sDivCol(10,'left',1);
			$CI->html->sBox('solid');
				$CI->html->sBoxBody(array('class'=>'paper'));
					$CI->html->sForm("academic/years_db","general-form");
						$CI->html->hidden('id',iSetObj($det,'id'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->H(4,"General Information",array('class'=>'form-titler'));
								$CI->html->inputPaper('Name:','name',iSetObj($det,'name'),null,array('class'=>'rOkay'));
								$CI->html->inputPaper('Start Date:','start_date',(iSetObjDate($det,'start_date')),null,array('class'=>'pick-date'),"fa-calendar");
								$CI->html->inputPaper('End Date:','end_date',(iSetObjDate($det,'end_date')),null,array('class'=>'pick-date'),"fa-calendar");
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eForm();
				$CI->html->eBoxBody();
			$CI->html->eBox();
		$CI->html->eDivCol();
	$CI->html->eDivRow();
	return $CI->html->code();
}
function coursesPage($det=array(),$subjects=array()){
	$CI =& get_instance();
	$CI->html->sDivRow();
		$CI->html->sDivCol(10,'left',1);
			$CI->html->sBox('solid');
				$CI->html->sBoxBody(array('class'=>'paper'));
					$CI->html->sForm("academic/courses_db","general-form");
						$CI->html->hidden('id',iSetObj($det,'id'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(5);
								$CI->html->H(4,"General Information",array('class'=>'form-titler'));
								$CI->html->inputPaper('Code:','code',iSetObj($det,'code'),null,array('class'=>'rOkay'));
								$CI->html->inputPaper('Name:','name',iSetObj($det,'name'),null,array('class'=>'rOkay'));
								$CI->html->inputPaper('Description:','description',iSetObj($det,'description'),null,array('class'=>'rOkay'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->H(4,"",array('class'=>'page-header'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->H(4,"Subjects",array('class'=>'form-titler'));
									$CI->html->sDivRow();
										$CI->html->sDivCol(10);	
											$CI->html->subjectsDropPaper('Subject:','subject',null,null,array('class'=>'rOkay'));
										$CI->html->eDivCol();
										$CI->html->sDivCol(2,'right');
											$CI->html->button(fa('fa-plus').' ADD',array('id'=>'add-subj-btn','class'=>'btn-sm btn-flat'),'primary');	
										$CI->html->eDivCol();
									$CI->html->eDivRow();
									$CI->html->sDivRow();
										$CI->html->sDivCol(12);
											$CI->html->sTable(array('class'=>'table paper-table','id'=>'main-tbl'));
												$CI->html->sTablehead();
													$CI->html->sRow();
														$CI->html->th('Code');
														$CI->html->th('Name');
														$CI->html->th(' ');
													$CI->html->eRow();
												$CI->html->eTablehead();
												$CI->html->sTableBody();
													foreach ($subjects as $ctr => $row) {
														$CI->html->sRow(array('id'=>'row-'.$ctr));
															$link = $CI->html->A(fa('fa-remove fa-lg'),'#',array('class'=>'remove','id'=>'remove-'.$ctr,'ref'=>$ctr,'return'=>'true'));
															$CI->html->td($row['subj_code']);
															$CI->html->td($row['subj_name']);
															$CI->html->td($link,array('style'=>'text-align:right;'));
														$CI->html->eRow();
													}
												$CI->html->eTableBody();
											$CI->html->eTable();
										$CI->html->eDivCol();
									$CI->html->eDivRow();
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->H(4,"",array('class'=>'page-header'));
						$CI->html->H(4,"Items",array('class'=>'form-titler'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(10);
								$CI->html->sTable(array('class'=>'table paper-table','id'=>'items-tbl'));
									$CI->html->sTablehead();
										$CI->html->sRow();
											$CI->html->th('Item');
											$CI->html->th('Qty');
											$CI->html->th('UOM');
											$CI->html->th('Price');
											$CI->html->th('Subtotal');
											$CI->html->th(' ');
										$CI->html->eRow();
									$CI->html->eTablehead();
									$CI->html->sTableBody();
										$CI->html->sRow(array('class'=>'form-row'));
											$CI->html->sTd(array('style'=>'width:300px;'));
												$CI->html->itemsDrop("","item_id",null,null,array('class'=>'rtbl-input paper-select show-tick','data-live-search'=>'true'));
											$CI->html->eTd();
											$CI->html->sTd(array('style'=>'width:80px;'));
												$CI->html->input("","qty",null,null,array('class'=>'rtbl-input paper-input'));
											$CI->html->eTd();
											$CI->html->sTd();
												$CI->html->span("",array('id'=>'uom-txt','class'=>'rtbl-input'));
												$CI->html->hidden("uom",null,array('class'=>'rtbl-input'));
											$CI->html->eTd();
											$CI->html->sTd();
												$CI->html->span(num(0),array('id'=>'price-txt','class'=>'rtbl-input'));
												$CI->html->hidden("price",null,array('class'=>'rtbl-input'));
											$CI->html->eTd();
											$CI->html->sTd();
												$CI->html->span(num(0),array('id'=>'total-txt','class'=>'rtbl-input'));
											$CI->html->eTd();
											$CI->html->sTd(array('style'=>'text-align:right'));
												// $CI->html->A(fa('fa-trash fa-lg'),'#',array('class'=>''));
											$CI->html->eTd();
										$CI->html->eRow();	
									$CI->html->eTableBody();
								$CI->html->eTable();
							$CI->html->eDivCol();
						$CI->html->eDivRow();


					$CI->html->eForm();
				$CI->html->eBoxBody();
			$CI->html->eBox();
		$CI->html->eDivCol();
	$CI->html->eDivRow();
	return $CI->html->code();
}
function batchesPage($det=array()){
	$CI =& get_instance();
	$CI->html->sDivRow();
		$CI->html->sDivCol(10,'left',1);
			$CI->html->sBox('solid');
				$CI->html->sBoxBody(array('class'=>'paper'));
					$CI->html->sForm("academic/batches_db","general-form");
						$CI->html->hidden('id',iSetObj($det,'id'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->H(4,"General Information",array('class'=>'form-titler'));
								$CI->html->inputPaper('Code:','code',iSetObj($det,'code'),null,array('class'=>'rOkay'));
								$CI->html->inputPaper('Name:','name',iSetObj($det,'name'),null,array('class'=>'rOkay'));
								$CI->html->courseDropPaper('Course:','course_id',iSetObj($det,'course_id'),null,array('class'=>'rOkay'));
								$CI->html->inputPaper('Start Date:','start_date',(iSetObjDate($det,'start_date')),null,array('class'=>'pick-date'),"fa-calendar");
								$CI->html->inputPaper('End Date:','end_date',(iSetObjDate($det,'end_date')),null,array('class'=>'pick-date'),"fa-calendar");
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eForm();
				$CI->html->eBoxBody();
			$CI->html->eBox();
		$CI->html->eDivCol();
	$CI->html->eDivRow();
	return $CI->html->code();
}
function subjectsPage($det=array()){
	$CI =& get_instance();
	$CI->html->sDivRow();
		$CI->html->sDivCol(10,'left',1);
			$CI->html->sBox('solid');
				$CI->html->sBoxBody(array('class'=>'paper'));
					$CI->html->sForm("academic/subjects_db","general-form");
						$CI->html->hidden('id',iSetObj($det,'id'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->H(4,"General Information",array('class'=>'form-titler'));
								$CI->html->inputPaper('Code:','code',iSetObj($det,'code'),null,array('class'=>'rOkay'));
								$CI->html->inputPaper('Name:','name',iSetObj($det,'name'),null,array('class'=>'rOkay'));
								$CI->html->inputPaper('Description:','description',iSetObj($det,'description'),null,array('class'=>'rOkay'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eForm();
				$CI->html->eBoxBody();
			$CI->html->eBox();
		$CI->html->eDivCol();
	$CI->html->eDivRow();
	return $CI->html->code();
}