<?php
function enrollmentForm($now=null,$next_ref=null){
	$CI =& get_instance();
		$CI->html->sForm("enrollment/db","enrollment-form");
		$CI->html->sBox('solid');
			$CI->html->sBoxBody();
				$CI->html->sDivRow();
					$CI->html->sDivCol(5);
						$CI->html->studentsDropPaper("Student:","student");
						$CI->html->courseDropPaper("Course:","course");
						$CI->html->batchDropPaper("Batch:","batch");
						$CI->html->sectionsDropPaper("Section:","section");
					$CI->html->eDivCol();
					$CI->html->sDivCol(3);
						$CI->html->inputPaper('Reference:',"trans_ref",$next_ref,null);
						$CI->html->inputPaper('Trans Date:',"trans_date",sql2Date($now),null,array('class'=>'pick-date'));
					$CI->html->eDivCol();
					$CI->html->sDivCol(4,'right');
						$url = base_url().'dist/img/no-photo.jpg';
						$CI->html->img($url,array('style'=>'height:150px;','class'=>'media-object thumbnail pull-right','id'=>'std-img'));
					$CI->html->eDivCol();
				$CI->html->eDivRow();
				$CI->html->sTab(array('class'=>'paper-tab','style'=>'margin-top:5px;'));
					$tabs = array(fa('fa-book').' Subjects'=>array('href'=>'#subjects-pane'),
								  fa('fa-cubes').' Items'=>array('href'=>'#items-pane'),
								  fa('fa-money').' Payment'=>array('href'=>'#payments-pane'),
								 );
					$CI->html->tabHead($tabs,null,array());
					$CI->html->sTabBody();
						$CI->html->sTabPane(array('id'=>'subjects-pane','class'=>'tab-pane active'));
							$CI->html->sDivRow();
								$CI->html->sDivCol(6);
									$CI->html->sTable(array('class'=>'table paper-table','id'=>'subjects-tbl'));
										$CI->html->sTablehead();
											$CI->html->sRow();
												$CI->html->th('Code');
												$CI->html->th('Name');
											$CI->html->eRow();
										$CI->html->eTablehead();
										$CI->html->sTableBody();
										$CI->html->eTableBody();
									$CI->html->eTable();
								$CI->html->eDivCol();
							$CI->html->eDivRow();	
						$CI->html->eTabPane();
						$CI->html->sTabPane(array('id'=>'items-pane','class'=>'tab-pane'));
							$CI->html->sTable(array('class'=>'table paper-table','id'=>'items-tbl'));
								$CI->html->sTablehead();
									$CI->html->sRow();
										$CI->html->th('Item');
										$CI->html->th('Qty');
										$CI->html->th('UOM');
										$CI->html->th('Price');
										$CI->html->th('Subtotal');
										$CI->html->th('');
									$CI->html->eRow();
								$CI->html->eTablehead();
								$CI->html->sTableBody();
									$CI->html->sRow();
										$CI->html->td('');
										$CI->html->td('');
										$CI->html->td('');
										$CI->html->td('<b>Grand Total</b>');
										$CI->html->td(num(0),array('id'=>'grand-total-txt'));
										$CI->html->td('');
									$CI->html->eRow();
								$CI->html->eTableBody();
							$CI->html->eTable();
						$CI->html->eTabPane();
						$CI->html->sTabPane(array('id'=>'payments-pane','class'=>'tab-pane'));
							$CI->html->sDivRow();
								$CI->html->sDivCol(5);
									$CI->html->hidden('pay_term_id',3);
									$CI->html->hidden('no_months',0);
									$CI->html->hidden('down_payment',0);
									$CI->html->hidden('dp_use_1',1);
									$CI->html->hidden('total_payment',0);
									$CI->html->hidden('day_of_month',5);
									$CI->html->inputPaper('Date Range:','date_range',null,null,array('class'=>''),'fa-calendar');
								$CI->html->eDivCol();
								$CI->html->sDivCol(5,'left',2);
									$CI->html->textPaper('Total Payment: ',num(0),array('id'=>'payment-total-txt'));
									$CI->html->textPaper('Total Months: ',num(0,0),array('id'=>'total-months-txt'));
								$CI->html->eDivCol();
							$CI->html->eDivRow();
							$CI->html->sDivRow(array('style'=>'margin-top:10px;'));
								$CI->html->sDivCol();
									$CI->html->sTable(array('class'=>'table paper-table','id'=>'payments-tbl'));
										$CI->html->sTablehead();
											$CI->html->sRow();
												$CI->html->th('#',array('style'=>'width:30px;'));
												$CI->html->th('Particular');
												$CI->html->th('Due Date');
												$CI->html->th('Amount Due');
											$CI->html->eRow();
										$CI->html->eTablehead();
										$CI->html->sTableBody();

										$CI->html->eTableBody();
									$CI->html->eTable();
								$CI->html->eDivCol();
							$CI->html->eDivRow();
						$CI->html->eTabPane();
					$CI->html->eTabBody();
				$CI->html->eTab();			
			$CI->html->eBoxBody();
		$CI->html->eBox();
		$CI->html->eForm();
	return $CI->html->code();
}
