<?php
function paymentForm($now=null,$next_ref=null,$det=array()){
	$CI =& get_instance();
	$CI->html->sBox('solid');
		$CI->html->sBoxBody();
			$CI->html->sDivRow();
				$CI->html->sDivCol(4);
					$CI->html->studentsDropPaper("Student:","student",null);
				$CI->html->eDivCol();
				$CI->html->sDivCol(4);
					$CI->html->inputPaper('Reference:',"trans_ref",$next_ref,null,array());
				$CI->html->eDivCol();
				$CI->html->sDivCol(4);
					$date = sql2Date($now);
					$CI->html->inputPaper('Trans Date:',"trans_date",$date,null,array('class'=>'pick-date'));
				$CI->html->eDivCol();
			$CI->html->eDivRow();
			$CI->html->sTab(array('class'=>'paper-tab','style'=>'margin-top:5px;'));
				$tabs = array(fa('fa-money').' Cash'=>array('href'=>'#cash-pane'),
							  fa('fa-credit-card').' Credit Card'=>array('href'=>'#credit-pane'),
							  fa('fa-pencil-square').' Check'=>array('href'=>'#check-pane'),
							 );
				$CI->html->tabHead($tabs,null,array());
				$CI->html->sTabBody();
					$CI->html->sTabPane(array('id'=>'cash-pane','class'=>'tab-pane active'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(3);
								$CI->html->inputPaper('Amount:','cash_amt',null,null,array('class'=>''),'fa-money');
							$CI->html->eDivCol();
							$CI->html->sDivCol(3);
								$CI->html->button("ADD",array('class'=>'btn-flat btn-sm'),'primary');
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eTabPane();
					$CI->html->sTabPane(array('id'=>'credit-pane','class'=>'tab-pane'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(2);
								$CI->html->inputPaper('Amount:','credit_amt',null,null,array('class'=>''),'fa-money');
							$CI->html->eDivCol();
							$CI->html->sDivCol(3);
								$CI->html->inputPaper('Bank:','credit_bank',null,null,array('class'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(3);
								$CI->html->inputPaper('Card No.:','credit_bank',null,null,array('class'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(3);
								$CI->html->inputPaper('Approval Code:','credit_bank',null,null,array('class'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(1);
								$CI->html->button("ADD",array('class'=>'btn-flat btn-sm'),'primary');
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eTabPane();
					$CI->html->sTabPane(array('id'=>'check-pane','class'=>'tab-pane'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(2);
								$CI->html->inputPaper('Amount:','check_amt',null,null,array('class'=>''),'fa-money');
							$CI->html->eDivCol();
							$CI->html->sDivCol(3);
								$CI->html->inputPaper('Bank:','check_bank',null,null,array('class'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(2);
								$CI->html->inputPaper('Branch:','credit_bank',null,null,array('class'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(2);
								$CI->html->inputPaper('Check No.:','check_no',null,null,array('class'=>'pick-date'));
							$CI->html->eDivCol();
							$CI->html->sDivCol(2);
								$CI->html->inputPaper('Check Date:','check_date',sql2Date($now),null,array('class'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(1);
								$CI->html->button("ADD",array('class'=>'btn-flat btn-sm'),'primary');
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eTabPane();
				$CI->html->eTabBody();
			$CI->html->eTab();		
			$CI->html->H(4,"",array('class'=>'page-header'));
			$CI->html->sDivRow();
				$CI->html->sDivCol();
					$CI->html->sTable(array('class'=>'table paper-table','id'=>'sched-tbl'));
						$CI->html->sTablehead();
							$CI->html->sRow();
								$CI->html->th('Particular');
								$CI->html->th('Due Date');
								$CI->html->th('Due Amount');
								$CI->html->th('Amount Paid');
								$CI->html->th('Balance');
								$CI->html->th('Amount Tender');
								$CI->html->th('');
							$CI->html->eRow();
						$CI->html->eTablehead();
						$CI->html->sTableBody();
						$CI->html->eTableBody();
					$CI->html->eTable();
				$CI->html->eDivCol();
			$CI->html->eDivRow();
		$CI->html->eBoxBody();
	$CI->html->eBox();
	return $CI->html->code();
}


